# -*- coding: utf-8 -*-
################################################################################
## Form generated from reading UI file 'tela.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################



#OBS: Esse arquivo foi mantinto como backup do arquivo tela.py

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QGraphicsView, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1256, 892)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.btn_open = QAction(MainWindow)
        self.btn_open.setObjectName(u"btn_open")
        self.btn_savefile = QAction(MainWindow)
        self.btn_savefile.setObjectName(u"btn_savefile")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 10, 81, 18))
        self.groupBoxWindow = QGroupBox(self.centralwidget)
        self.groupBoxWindow.setObjectName(u"groupBoxWindow")
        self.groupBoxWindow.setGeometry(QRect(10, 610, 301, 231))
        self.btn_win_up = QPushButton(self.groupBoxWindow)
        self.btn_win_up.setObjectName(u"btn_win_up")
        self.btn_win_up.setGeometry(QRect(110, 60, 88, 26))
        self.btn_win_right = QPushButton(self.groupBoxWindow)
        self.btn_win_right.setObjectName(u"btn_win_right")
        self.btn_win_right.setGeometry(QRect(210, 110, 88, 26))
        self.btn_win_left = QPushButton(self.groupBoxWindow)
        self.btn_win_left.setObjectName(u"btn_win_left")
        self.btn_win_left.setGeometry(QRect(10, 110, 88, 26))
        self.btn_win_down = QPushButton(self.groupBoxWindow)
        self.btn_win_down.setObjectName(u"btn_win_down")
        self.btn_win_down.setGeometry(QRect(110, 150, 88, 26))
        self.btn_rot_left = QPushButton(self.groupBoxWindow)
        self.btn_rot_left.setObjectName(u"btn_rot_left")
        self.btn_rot_left.setGeometry(QRect(10, 40, 88, 26))
        self.btn_rot_right = QPushButton(self.groupBoxWindow)
        self.btn_rot_right.setObjectName(u"btn_rot_right")
        self.btn_rot_right.setGeometry(QRect(210, 40, 88, 26))
        self.escala_translacao = QLineEdit(self.groupBoxWindow)
        self.escala_translacao.setObjectName(u"escala_translacao")
        self.escala_translacao.setGeometry(QRect(110, 110, 91, 26))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.escala_translacao.sizePolicy().hasHeightForWidth())
        self.escala_translacao.setSizePolicy(sizePolicy1)
        self.escala_translacao.setMaxLength(5)
        self.escala_translacao.setAlignment(Qt.AlignCenter)
        self.btn_reset_window = QPushButton(self.groupBoxWindow)
        self.btn_reset_window.setObjectName(u"btn_reset_window")
        self.btn_reset_window.setGeometry(QRect(110, 200, 88, 26))
        self.btn_win_zoom_in = QPushButton(self.groupBoxWindow)
        self.btn_win_zoom_in.setObjectName(u"btn_win_zoom_in")
        self.btn_win_zoom_in.setGeometry(QRect(220, 150, 61, 61))
        icon = QIcon()
        iconThemeName = u"zoom-in"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)
        
        self.btn_win_zoom_in.setIcon(icon)
        self.btn_win_zoom_in.setIconSize(QSize(20, 20))
        self.btn_win_zoom_out = QPushButton(self.groupBoxWindow)
        self.btn_win_zoom_out.setObjectName(u"btn_win_zoom_out")
        self.btn_win_zoom_out.setGeometry(QRect(20, 150, 61, 61))
        icon1 = QIcon()
        iconThemeName = u"zoom-out"
        if QIcon.hasThemeIcon(iconThemeName):
            icon1 = QIcon.fromTheme(iconThemeName)
        else:
            icon1.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)
        
        self.btn_win_zoom_out.setIcon(icon1)
        self.btn_win_zoom_out.setIconSize(QSize(20, 20))
        self.groupBoxObject = QGroupBox(self.centralwidget)
        self.groupBoxObject.setObjectName(u"groupBoxObject")
        self.groupBoxObject.setGeometry(QRect(470, 610, 781, 231))
        self.list_itens_object = QListWidget(self.groupBoxObject)
        self.list_itens_object.setObjectName(u"list_itens_object")
        self.list_itens_object.setGeometry(QRect(10, 61, 256, 161))
        self.btn_add_point_object = QPushButton(self.groupBoxObject)
        self.btn_add_point_object.setObjectName(u"btn_add_point_object")
        self.btn_add_point_object.setGeometry(QRect(310, 140, 101, 26))
        self.btn_update_point_object = QPushButton(self.groupBoxObject)
        self.btn_update_point_object.setObjectName(u"btn_update_point_object")
        self.btn_update_point_object.setGeometry(QRect(310, 170, 101, 26))
        self.groupBoxWindow_2 = QGroupBox(self.groupBoxObject)
        self.groupBoxWindow_2.setObjectName(u"groupBoxWindow_2")
        self.groupBoxWindow_2.setGeometry(QRect(440, 40, 301, 171))
        self.btn_obj_up = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_up.setObjectName(u"btn_obj_up")
        self.btn_obj_up.setGeometry(QRect(110, 30, 88, 26))
        self.btn_obj_right = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_right.setObjectName(u"btn_obj_right")
        self.btn_obj_right.setGeometry(QRect(210, 80, 88, 26))
        self.btn_obj_left = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_left.setObjectName(u"btn_obj_left")
        self.btn_obj_left.setGeometry(QRect(10, 80, 88, 26))
        self.btn_obj_down = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_down.setObjectName(u"btn_obj_down")
        self.btn_obj_down.setGeometry(QRect(110, 120, 88, 26))
        self.btn_obj_rot_left = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_rot_left.setObjectName(u"btn_obj_rot_left")
        self.btn_obj_rot_left.setGeometry(QRect(10, 40, 88, 26))
        self.btn_obj_rot_right = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_rot_right.setObjectName(u"btn_obj_rot_right")
        self.btn_obj_rot_right.setGeometry(QRect(210, 40, 88, 26))
        self.escala_translacao_obj = QLineEdit(self.groupBoxWindow_2)
        self.escala_translacao_obj.setObjectName(u"escala_translacao_obj")
        self.escala_translacao_obj.setGeometry(QRect(110, 80, 91, 26))
        sizePolicy1.setHeightForWidth(self.escala_translacao_obj.sizePolicy().hasHeightForWidth())
        self.escala_translacao_obj.setSizePolicy(sizePolicy1)
        self.escala_translacao_obj.setMaxLength(5)
        self.escala_translacao_obj.setAlignment(Qt.AlignCenter)
        self.btn_obj_zoom_in = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_zoom_in.setObjectName(u"btn_obj_zoom_in")
        self.btn_obj_zoom_in.setGeometry(QRect(220, 120, 61, 41))
        self.btn_obj_zoom_in.setIcon(icon)
        self.btn_obj_zoom_out = QPushButton(self.groupBoxWindow_2)
        self.btn_obj_zoom_out.setObjectName(u"btn_obj_zoom_out")
        self.btn_obj_zoom_out.setGeometry(QRect(20, 120, 61, 41))
        self.btn_obj_zoom_out.setIcon(icon1)
        self.coordx_select_point_object = QDoubleSpinBox(self.groupBoxObject)
        self.coordx_select_point_object.setObjectName(u"coordx_select_point_object")
        self.coordx_select_point_object.setGeometry(QRect(331, 61, 67, 27))
        self.coordy_select_point_object = QDoubleSpinBox(self.groupBoxObject)
        self.coordy_select_point_object.setObjectName(u"coordy_select_point_object")
        self.coordy_select_point_object.setGeometry(QRect(331, 94, 67, 27))
        self.label_2 = QLabel(self.groupBoxObject)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(311, 61, 16, 18))
        self.label_3 = QLabel(self.groupBoxObject)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(311, 94, 16, 18))
        self.label_5 = QLabel(self.groupBoxObject)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(11, 31, 35, 18))
        self.current_object_row = QLineEdit(self.groupBoxObject)
        self.current_object_row.setObjectName(u"current_object_row")
        self.current_object_row.setEnabled(False)
        self.current_object_row.setGeometry(QRect(52, 31, 125, 26))
        self.current_object_row.setAlignment(Qt.AlignCenter)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 30, 1251, 561))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.objectslist = QListWidget(self.layoutWidget)
        self.objectslist.setObjectName(u"objectslist")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.objectslist.sizePolicy().hasHeightForWidth())
        self.objectslist.setSizePolicy(sizePolicy2)

        self.horizontalLayout.addWidget(self.objectslist)

        self.viewport = QGraphicsView(self.layoutWidget)
        self.viewport.setObjectName(u"viewport")

        self.horizontalLayout.addWidget(self.viewport)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(320, 610, 141, 231))
        self.create_new_object = QPushButton(self.groupBox)
        self.create_new_object.setObjectName(u"create_new_object")
        self.create_new_object.setGeometry(QRect(20, 40, 101, 26))
        self.update_new_object = QPushButton(self.groupBox)
        self.update_new_object.setObjectName(u"update_new_object")
        self.update_new_object.setGeometry(QRect(20, 80, 101, 26))
        self.btn_leave_obj = QPushButton(self.groupBox)
        self.btn_leave_obj.setObjectName(u"btn_leave_obj")
        self.btn_leave_obj.setGeometry(QRect(20, 120, 101, 26))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1256, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.btn_open)
        self.menuFile.addAction(self.btn_savefile)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_open.setText(QCoreApplication.translate("MainWindow", u"Open File", None))
        self.btn_savefile.setText(QCoreApplication.translate("MainWindow", u"Save File", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Objects List", None))
        self.groupBoxWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window Control", None))
        self.btn_win_up.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.btn_win_right.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.btn_win_left.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.btn_win_down.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.btn_rot_left.setText(QCoreApplication.translate("MainWindow", u"RotLeft", None))
        self.btn_rot_right.setText(QCoreApplication.translate("MainWindow", u"RotRigth", None))
        self.escala_translacao.setInputMask("")
        self.btn_reset_window.setText(QCoreApplication.translate("MainWindow", u"Resert", None))
        self.btn_win_zoom_in.setText("")
        self.btn_win_zoom_out.setText("")
        self.groupBoxObject.setTitle(QCoreApplication.translate("MainWindow", u"Object", None))
        self.btn_add_point_object.setText(QCoreApplication.translate("MainWindow", u"Add Point", None))
        self.btn_update_point_object.setText(QCoreApplication.translate("MainWindow", u"Update Point", None))
        self.groupBoxWindow_2.setTitle(QCoreApplication.translate("MainWindow", u"Object Control", None))
        self.btn_obj_up.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.btn_obj_right.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.btn_obj_left.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.btn_obj_down.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.btn_obj_rot_left.setText(QCoreApplication.translate("MainWindow", u"RotLeft", None))
        self.btn_obj_rot_right.setText(QCoreApplication.translate("MainWindow", u"RotRigth", None))
        self.escala_translacao_obj.setInputMask("")
        self.btn_obj_zoom_in.setText("")
        self.btn_obj_zoom_out.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Row:", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Objects List Control", None))
        self.create_new_object.setText(QCoreApplication.translate("MainWindow", u"Create Object", None))
        self.update_new_object.setText(QCoreApplication.translate("MainWindow", u"Update Object", None))
        self.btn_leave_obj.setText(QCoreApplication.translate("MainWindow", u"Leave Object", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

